# Site settings
title: Jingzhe Blog
SEOTitle: 惊蛰的博客 | Jingzhe Blog
header-img: img/post-bg-desk.jpg
email: bin19952016@outlook.com
description: "Every failure is leading towards success."
keyword: "惊蛰,惊蛰的博客"
url: "https://binmumu.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/binmumu/binmumu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "思考、行走、回首"
sidebar-avatar: /img/about-Jingzhe-man.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
github_username:    binmumu

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e900a0f4fcb896b895e0   #生成的clientID
  clientSecret: 5c642ceb3c2f31bf91406bd50559f19c73cab75f  #同上
  repo: binmumu.github.io    #仓库名称
  owner: binmumu   #github用户名
  admin: binmumu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 681ebca8aeacc0123c76c22681f7c0b7

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

